# This workflow will do a clean install of node dependencies and build the source code

name: Node.js Build

on:
  push:
    branches: [ master, chartjs3 ]
  pull_request:
    branches: [ master, chartjs3 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: actions/upload-artifact@v2
      with:
        name: Minified JavaScript bundle
        path: dist/*.min.js
        if-no-files-found: error
